config/routes.rb
Rails.application.routes.draw do
	resources :kittens

	get '/sidebar', to: 'static_pages#sidebar'
	get '/form'		, to: 'static_pages#form'


	root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	# validates: name, {max_lenght: [20]}
	validates :name, 			presence: true, length: { maximum: 20 }
	validates :age,				presence: true
	validates :cuteness, 	presence: true
	validates :softness, 	presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

	def index
		@kittens = Kitten.all
		respond_to do |format|
			format.html
			format.json { render :json => @kittens }
		end
	end

	def show
		@kitten  = Kitten.find(params[:id])
		respond_to do |format|
			format.html
			format.json { render :json => @kitten }
		end
	end

	def new
		@kitten  = Kitten.new
	end

	def create
		@kitten  = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success] = "Kitten succesfully created"
			redirect_to @kitten
		else
			render inline: "<h1>oh no</h1>"
		end
	end

	def edit
		@kitten  = Kitten.find(params[:id])
	end

	def update
		@kitten  = Kitten.find(params[:id])
		if @kitten.update(kitten_params)
			flash[:success] = "Kitten succesfully edited"
			redirect_to @kitten
		else
			render :edit
		end
	end

	def destroy
		@kitten  = Kitten.find(params[:id])
		@kitten.delete
		flash[:success] = "Kitten succesfully killed"
		redirect_to kittens_path
	end

	private
		def kitten_params
			params.require(:kitten).permit(:name, :age, :cuteness, :softness)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	include FlickrHelper
	def form
		if params[:name]
			@user   = params[:name]
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flickr_helper.rb
module FlickrHelper
	def setup
		data = YAML.load_file("config/flickr.yml")
		FlickRaw.api_key 			 = data["key"]
		FlickRaw.shared_secret = data["secret"]
	end

	def user_photos(user_id, photo_count = 12)
		setup
		flickr.photos.search(:user_id => user_id).first(photo_count)
	end

	def get_url(photo)
		FlickRaw.url(flickr.photos.getInfo(:photo_id => photo.id))
	end

	def render_flickr_sidebar_widget(user_id, photo_count = 12, columns = 2)
		begin
			photos = user_photos(user_id, photo_count).in_groups_of(columns)
			render :partial => '/flickr/sidebar_widget', :locals => { :photos => photos }
		rescue Exception
			render :partial => '/flickr/unavailable'
		end
	end

	def user_exists?(user)
		setup
		begin
			flickr.people.findByUsername(username: user) 
		rescue
			false
		end
	end
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/flickr/_sidebar_widget.html.erb
<head>
	<style>
		.flickr ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
		}

		.flickr ul li {
			border-bottom: 0;
			margin: 0;
			padding: 0;
		}

		.flickr_photo{
			width: 75px;
			height: 75px;
			padding: 12px 10px 32px 13px;
			margin: 0
			background: #fff;
		}
	</style>
</head>

<div class="flickr">
	<ul>
		<% photos.each do |row| %>
			<li>
				<% row.each do |p| %>
					<%= link_to(image_tag(get_url(p),
							:class 	=> 'flickr_photo', 
							:title 	=> p.title, 
							:border => 0, 
							:size 	=> '75x75'),
						 get_url(p)) %>
				<% end %>
			</li>
		<% end %>
	</ul>
</div>

app/views/flickr/_unavailable.html.erb
this is not working, dammit

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
	<% if @kitten.errors.any? %>
		<ul>
			<% @kitten.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :age %>
	<%= f.select(:age,			options_for_select(1..30)) %>

	<%= f.label :cuteness %>
	<%= f.select(:cuteness, options_for_select(0..10)) %>

	<%= f.label :softness %>
	<%= f.select(:softness, options_for_select(0..10)) %>

	<%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render 'form' %>

app/views/kittens/index.html.erb
<h1>Kittenz!</h1>

<p>this app sends JSON data of the Kittens, both on the index page and in the show page for every single kitten</p>

<h2><%= link_to 'new kitten', new_kitten_path %></h2>

<h2>kittens list</h2>

<ol>
	<% @kittens.each do |cat| %>
		<li>
			<%= link_to cat.name, cat %>
			<%= link_to "kill",   cat, method: :delete %>			
		</li>
	<% end %>
</ol>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render 'form' %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %>'s page</h1>

<table>
	<tr>
		<th>age</th>
		<td><%= @kitten.age 		 %></td>
	</tr>
	<tr>
		<th>cuteness</th>
		<td><%= @kitten.cuteness %></td>
	</tr>
	<tr>		
		<th>softness</th>
		<td><%= @kitten.softness %></td>
	</tr>
</table>

<%= link_to "<< all kittens", kittens_path %>
<%= link_to "edit",	  edit_kitten_path %>
<%= link_to "delete", @kitten, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |message_type, message| %>
  		<div class="alert alert-<%= message_type %>">
  			<%= message %>
			</div>
  	<% end %>
    <%= yield %>
    <%= link_to "HOME", root_path %>
  </body>
</html>

app/views/static_pages/form.html.erb
<h1>Search Images on Flickr</h1>
<p>the form is slow because Flickr's API is not incredibly fast, so have some patience</p>

<%= form_tag('/form', method: :get) do %>
		<%= label_tag(:name) %>
		<%= text_field_tag(:name) %>
		<%= submit_tag("search") %>
<% end %>

<% if @user %>
	<% if user_exists?(@user) %>
		<p>displaying pictures for user <strong><%= @user %></strong></p>
		<% user_photos(@user).each do |p| %>
			<%= link_to(image_tag(get_url(p),
								:class 	=> 'flickr_photo', 
								:title 	=> p.title, 
								:border => 0, 
								:size 	=> '200'),
							 get_url(p)) %>
		<% end %>
	<% else %>
		<p>User not found</p>
	<% end %>
<% end %>
<br>

app/views/static_pages/index.html.erb
<h1>Kittenz!</h1>


<h2>
	<%= link_to "Project 1: Building a Simple Kittens API", kittens_path %>
</h2>
<ol>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
</ol>


<h2>Project 2: Using a Third Party API</h2>
<ol>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
	<li>☐ store the key in an environment variable instead and/or use a gem like figaro</li>
	<li>☑</li>
	<li>☑</li>
	<li>☑</li>
</ol>

<ul>
	<li><%= link_to "Flickr sidebar (slow to load)", sidebar_path %></li>
	<li><%= link_to "Flickr User pictures", form_path %></li>
</ul>

<h3>stuff to do</h3>
<ul>
	<li>css</li>
	<li>css for flash</li>
	<li>better flash (pluralization and count)</li>
	<li>navigation</li>
	<li>APIs in and APIs out explanations</li>
	<li>new page for the pictures</li>
	<li>pictures of cats, maybe by tag</li>
	<li>sidebar actually on the side(css)</li>
	<li>can select the user for the userbar</li>
	<li>implement figaro gem to store the secret key</li>
	<li>better link for the pictures (not the plain jpg)</li>
</ul>

app/views/static_pages/sidebar.html.erb
<h1>Flickr sidebar</h1>

<div>
	<p>The domestic cat (Felis catus[1][5] or Felis silvestris catus) is a small, typically furry, carnivorous mammal. They are often called house cats when kept as indoor pets or simply cats when there is no need to distinguish them from other felids and felines.[6] Cats are often valued by humans for companionship and for their ability to hunt vermin. There are more than 70 cat breeds, though different associations proclaim different numbers according to their standards.</p>
	<p>Cats are similar in anatomy to the other felids, with a strong flexible body, quick reflexes, sharp retractable claws, and teeth adapted to killing small prey. Cat senses fit a crepuscular and predatory ecological niche. Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals. They can see in near darkness. Like most other mammals, cats have poorer color vision and a better sense of smell than humans. Cats, despite being solitary hunters, are a social species and cat communication includes the use of a variety of vocalizations (mewing, purring, trilling, hissing, growling, and grunting), as well as cat pheromones and types of cat-specific body language.[7]</p>
</div>

<div>
	<% cache ("flickr_sidebar") do %>
	  <%= render_flickr_sidebar_widget('28439801@N02') %>
	<% end %>
</div>